application:
  port: 8000
database:
  username: postgres
  password: password
  host: localhost
  port: 5432
  database_name: newsletter
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "token_mock"
  timeout_milliseconds: 10000
