application:
  host: 127.0.0.1
  hmac_secret: mock_secret_value_with_a_long_mock_value_containing_a_lot_of_characters
database:
  require_ssl: false
email_client:
  base_url: https://webhook.site/bdf7f5c8-a1b2-4780-bb18-c4739988d074
